#!/usr/bin/env bash
# Install HAproxy on your Load Balancer

# Update
apt-get -y update

# Install HAproxy
apt-get -y install haproxy

# Configure HAproxy
echo '
frontend web
	bind *:80
	default_backend servers

backend servers
	balance roundrobin
	server web-01 18.234.249.63:80 check
	server web-02 54.167.96.160:80 check
' >> /etc/haproxy/haproxy.cfg

# Test config
haproxy -f /etc/haproxy/haproxy.cfg -c

# Restart HAProxy
service haproxy restart
